### ISSUE TITLE
Verb Dictionary Traversal Resulting in Null Codes

### ISSUE THREAD

**Issue by efaurie** [openeventdata/UniversalPetrarch#13]
I can't seem to get event codes to properly output with my own input text (English) or the English GigaWord test files. It will output event triples but the verb code is always a null code ('---') or None.

I believe this is due to an improper traversal of the Verb Dictionary while resolving a verb to its code.
 
[Lines 1265-1266](https://github.com/openeventdata/UniversalPetrarch/blob/master/UniversalPetrarch/PETRgraph.py#L1265) and [Line 1583](https://github.com/openeventdata/UniversalPetrarch/blob/master/UniversalPetrarch/PETRgraph.py#L1583) in PETRgraph.py treat the final traversal (IE: `tempverbDictPath['#']['#']` in the case of 1265) as a dictionary when, in fact, it's a list of dictionaries. Which would imply that the lines should be something like the below instead.
```python
code = tempverbDictPath['#']['#'][0]['code']
meaning = tempverbDictPath['#']['#'][0]['meaning']
```

I have had to make a few modifications to get the code running at all (under both Python 2.7 and Python 3.6), so I don't want to submit a PR until I know it's not due to a bug I introduced.

Have others come across this? Has everyone else needed to make modifications to get the code running or has it worked out of the box?

**Comment by ahalterman** [comment]
This issue has come up a few times before, but sometimes the code does generate events 🤔. A PR fixing this and adding Python 3 compatibility would be very welcome! @JingL1014, does your latest commit fix this issue?

**Comment by JingL1014** [comment]
Yes. The latest commit fixed this issue. But it only works under Python 2.7.

**Comment by efaurie** [comment]
Closing this issue as the Verb Dictionary traversal is fixed with JingL1014's commit.
