### ISSUE TITLE
Example sentences that produce events

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/UniversalPetrarch#17]
@JingL1014, do you have any sentences you know should produce events? I've been trying to find some so I can write some unit tests to make sure `run_pipeline` is actually working, but I keep not getting any events back. Do you have any you know produce events? (Note, I'm looking for ones that use the real dictionaries, not the validation suite dictionaries).

**Comment by JingL1014** [comment]
I put some sentences in the attached file. If you need more sentences, please let me know.
[english_sample.xml.txt](https://github.com/openeventdata/UniversalPetrarch/files/1759959/english_sample.xml.txt)

**Comment by ahalterman** [comment]
Thanks! These work great.
