### ISSUE TITLE
Using lemmas (especially for Arabic)

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/UniversalPetrarch#20]
I wanted to check to make sure UniversalPetrarch is using the word lemmas, since this is an especially important issue for Arabic. [This line](https://github.com/openeventdata/UniversalPetrarch/blob/master/UniversalPetrarch/PETRgraph.py#L1097) seems to imply that it's potentially preferring the raw text instead of the lemmas. Am I reading that right, @JingL1014? More broadly, is UP working on lemmas instead of raw tokens?

**Comment by JingL1014** [comment]
For verbs, it is working on lemmas. But for nouns, it now checks raw text first and then checks lemma. Because the nouns in the English patterns are not all in lemma form now.

**Comment by khaledJabr** [comment]
This really a crucial point. Udpipe produced two lemmas for each verb, like the following: 
	قال	قَال	VERB	VP-A-3MS--
The difference between the two is that one contains short vowels (the left-most one), and one does not. Do you know which lemma is petrarch using here ?

**Comment by JingL1014** [comment]
![arabic_parsing](https://user-images.githubusercontent.com/11895289/37879969-c75e1618-3046-11e8-9e5d-ae0eea7bdae1.png)
From UDpipe, the first word is the original form and the second word is the lemma form. Right now UDpetrarch uses the lemma form of verbs. If the verbs of Arabic verb dictionary don't have diacritics, we can first use packages such as [PyArabic](https://pypi.python.org/pypi/PyArabic/0.6.2) to remove the diacritics of lemmas first and then do event coding.

**Comment by khaledJabr** [comment]
where in preprocessing exactly can I do that ?

**Comment by JingL1014** [comment]
You can modify the variable [parsed](https://github.com/openeventdata/UniversalPetrarch/blob/2c655c29260062a66c8901c4bfb246f56b28ffa7/UniversalPetrarch/preprocessing/generateParsedFile.py#L40) in the preprocessing code generateParsedFile.py by adding this additional preprocessing step. But this code is for all three languages, you need to add an argument to make sure this only works for Arabic inputs. Or you can write another code to only process Arabic documents.

**Comment by khaledJabr** [comment]
Ok. I have resolved this.
