### ISSUE TITLE
reading parsed articles error : 'sent_id' referenced before assignment

### ISSUE THREAD

**Issue by khaledJabr** [openeventdata/UniversalPetrarch#21]
I have been working with [this parsed file ](https://www.sendspace.com/file/g4hmf0)on Universal Petrarch. When I run Petrarch on it, it fails on reading the file, and gives this error: 
```
Traceback (most recent call last):
  File "petrarch_ud.py", line 471, in <module>
    main()
  File "petrarch_ud.py", line 81, in main
    run(paths, out , True)  ## <===
  File "petrarch_ud.py", line 423, in run
    events = PETRreader.read_xml_input(filepaths, s_parsed)
  File "...../UniversalPetrarch/PETRreader.py", line 2373, in read_xml_input
    holding[entry_id]['sents'][sent_id] = sent_dict
UnboundLocalError: local variable 'sent_id' referenced before assignment
```

I am suspecting this issue has to do with duplicate sentence/story id's, but I am not 100% sure. What I am currently doing is skipping those which cause this issue and it seems to be working.

**Comment by JingL1014** [comment]
yes, this error is due to the duplicated entry_id in the input file. I fixed the errors.
