### ISSUE TITLE
Why is Python3 code in a separate directory?

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/UniversalPetrarch#39]
Why is the Python 3 code in a separate directory in UniversalPetrarch instead of just converting the existing code to be 2/3 compatible? There's a big risk of the two code bases diverging unless every change to one gets manually copied over to the other.

**Comment by ahalterman** [comment]
I think it's okay to just have 3, though other people might think differently. The other option is to just re-write the Python 2/3 specific parts around `networkx` and execute different blocks based on which version is running.

**Comment by JingL1014** [comment]
The coder now is python 2/3 compatible, and I removed the directory python3/.
