### ISSUE TITLE
Spanish GSRs missing source/target CAMEO code

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/UniversalPetrarch#46]
I was just looking at the Spanish GSRs to make sure I matched the Arabic ones to them, and I noticed that while they have the source and target actor text, they don't actually have the actor CAMEO codes. Are there plans to add the actor codes? (I'm looking at [`spanish_protest_cameo_4_jj_validation`](https://github.com/openeventdata/UniversalPetrarch/blob/master/UniversalPetrarch/data/text/spanish_protest_cameo_4_jj_validation.xml))

**Comment by JingL1014** [comment]
Yes. Those will be added after the Spanish team finishes the validation.

**Comment by JingL1014** [comment]
The actor codes of Spanish validation set are added.
