### ISSUE TITLE
Print out dictionary line number on match

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/UniversalPetrarch#48]
(We've been talking about this for a while but wanted to consolidate as an issue @khaledJabr @philip-schrodt ).

Petrarch1 and Petrarch2 both had the ability to print out the dictionary line number of a match. This is very useful for debugging the dictionaries, since otherwise we don't know what pattern resulted in a coding. UniversalPetrarch does not have this ability and needs it so we can debug dictionaries.

**Comment by khaledJabr** [comment]
Here's the original issue for this https://github.com/openeventdata/UniversalPetrarch/issues/40 @JingL1014  already made a suggestion to do something similar, but it is not quite the same thing as we're looking for.

**Comment by ahalterman** [comment]
It sounds like this is resolved now. Is that right? If so, we should close.

**Comment by JingL1014** [comment]
Yes. This is solved.
