### ISSUE TITLE
PETRgraph.py is selecting verbs at random to generate events

### ISSUE THREAD

**Issue by philip-schrodt** [openeventdata/UniversalPetrarch#49]
The problem occurs in `get_events_from_petrarch1_patterns(self):` in the loop `for i in range(0,len(verbdata)):` that covers lines 3498-3562. This goes through a set of verbs in the  dictionary `verbdata`, order of these of course being random, and creates an event out of the first one it finds that has actors. The key-value pairs in Python dictionaries, however, are ordered randomly, so there is no guarantee that evaluating this loop twice with the same data will produce the same results, and in the current Spanish validation cases, this is happening a lot.

**Comment by JingL1014** [comment]
I fixed the errors and tested on my computer. Please try again and see if that is still happening.

**Comment by philip-schrodt** [comment]
3.5.0 -- I'll try upgrading and see if that corrects things

**Comment by philip-schrodt** [comment]
Upgraded to Python 3.7.1 (on Mac OS 10.13.6) and I'm getting deterministic results now. 
```
Records evaluated:    1016
Correct events:        576    45.14%
Uncoded events:        700    54.86%
Extra events:         3062   301.38%
```
These are slightly different than what I got running Python 2.7 (above) but beyond documenting this fact I don't think it's worth worrying about.
